export const FETCH_RESTAURENT_REQUEST = "FETCH_RESTAURENT_REQUEST";
export const FETCH_RESTAURENT_SUCCESS = "FETCH_RESTAURENT_SUCCESS";
export const FETCH_RESTAURENT_ERROR = "FETCH_RESTAURENT_ERROR";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_ERROR = "FETCH_CUSTOMER_ERROR";
