export const FETCH_RESTAURENT_REQUEST = "FETCH_RESTAURENT_REQUEST";
export const FETCH_RESTAURENT_SUCCESS = "FETCH_RESTAURENT_SUCCESS";
export const FETCH_RESTAURENT_ERROR = "FETCH_RESTAURENT_ERROR";
